version: '3.3'

networks:
  backend:
    driver: bridge

services:
  app:
    env_file:
      - .env
    build:
        context: .
        dockerfile: Dockerfile
    image: php:8.1
    container_name: app-test
    restart: unless-stopped
    tty: true
    environment:
        SERVICE_NAME: dev
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
        - backend

  ssh:
    build:
        context: .
        dockerfile: ./docker/ssh/Dockerfile
    container_name: ssh-test
    ports:
        - "3000:22"
    volumes:
        - ./:/var/www
    working_dir: /var/www
    networks:
        - backend

  nginx:
    build:
      context: docker/nginx
    container_name: nginx-test
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - backend

  db:
    build:
      context: ./docker/mysql
    container_name: db-test
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: db
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - db.test.loc

  php:
    build:
      context: ./docker/php-fpm
    container_name: php-test
    ports:
      - "9000:9000"
    networks:
      - backend
